--
-- calculate_limits
-- 

CREATE OR REPLACE FUNCTION calculate_limits(in mobileid int8, in typeid int8, out dailycount float8, out dailyamount numeric, out weeklycount float8, out weeklyamount numeric, out monthlycount float8, out monthlyamount numeric, out yearlycount float8, out yearlyamount numeric)
  RETURNS record AS 
$BODY$
   DECLARE
   MOBILENUMBER  MPAY_CUSTOMERMOBILES.MOBILENUMBER%TYPE;
BEGIN
   SELECT m.MOBILENUMBER INTO STRICT MOBILENUMBER FROM MPAY_CUSTOMERMOBILES m WHERE ID = MOBILEID;

   BEGIN
      SELECT SUM(TRANSACTIONS.TOTALAMOUNT) INTO STRICT DAILYAMOUNT FROM MPAY_TRANSACTIONS TRANSACTIONS, MPAY_ENDPOINTOPERATIONS OPERATIONS, MPAY_MPAYMESSAGES MESSAGES
      WHERE TRANSACTIONS.REFMESSAGEID = MESSAGES.ID
      AND MESSAGES.REFOPERATIONID = OPERATIONS.ID
      AND OPERATIONS.MESSAGETYPEID = TYPEID
      AND TRANSACTIONS.SENDERMOBILEID = MOBILEID
      AND TRUNC(TRANSACTIONS.TRANSDATE) = DATE_TRUNC('DAY',LOCALTIMESTAMP)
      AND TRANSACTIONS.PROCESSINGSTATUSID IN(1,2,4);
      IF DAILYAMOUNT IS NULL THEN
         DAILYAMOUNT := 0;
      END IF;
   END;
   SELECT COUNT(MESSAGES.ID) INTO STRICT DAILYCOUNT FROM MPAY_MPAYMESSAGES MESSAGES, MPAY_ENDPOINTOPERATIONS OPERATIONS
   WHERE MESSAGES.REFOPERATIONID = OPERATIONS.ID
   AND OPERATIONS.MESSAGETYPEID = TYPEID
   AND MESSAGES.SENDER = MOBILENUMBER
   AND TRUNC(MESSAGES.PROCESSINGSTAMP) = DATE_TRUNC('DAY',LOCALTIMESTAMP)
   AND MESSAGES.PROCESSINGSTATUSID IN(1,2,4);
   BEGIN
      SELECT SUM(TRANSACTIONS.TOTALAMOUNT) INTO STRICT WEEKLYAMOUNT FROM MPAY_TRANSACTIONS TRANSACTIONS, MPAY_ENDPOINTOPERATIONS OPERATIONS, MPAY_MPAYMESSAGES MESSAGES
      WHERE TRANSACTIONS.REFMESSAGEID = MESSAGES.ID
      AND MESSAGES.REFOPERATIONID = OPERATIONS.ID
      AND OPERATIONS.MESSAGETYPEID = TYPEID
      AND TRANSACTIONS.SENDERMOBILEID = MOBILEID
      AND EXTRACT(YEAR FROM TRANSACTIONS.TRANSDATE) =  EXTRACT(YEAR FROM LOCALTIMESTAMP)
      AND CAST(TO_CHAR(TRANSACTIONS.TRANSDATE,'WW') AS DOUBLE PRECISION) =  CAST(TO_CHAR(LOCALTIMESTAMP,'WW') AS BIGINT)
      AND TRANSACTIONS.PROCESSINGSTATUSID IN(1,2,4);
      IF WEEKLYAMOUNT IS NULL THEN
         WEEKLYAMOUNT := 0;
      END IF;
   END;

   SELECT COUNT(MESSAGES.ID) INTO STRICT WEEKLYCOUNT FROM MPAY_MPAYMESSAGES MESSAGES, MPAY_ENDPOINTOPERATIONS OPERATIONS
   WHERE MESSAGES.REFOPERATIONID = OPERATIONS.ID
   AND OPERATIONS.MESSAGETYPEID = TYPEID
   AND MESSAGES.SENDER = MOBILENUMBER
   AND EXTRACT(YEAR FROM MESSAGES.PROCESSINGSTAMP) =  EXTRACT(YEAR FROM LOCALTIMESTAMP)
   AND CAST(TO_CHAR(MESSAGES.PROCESSINGSTAMP,'WW') AS DOUBLE PRECISION) =  CAST(TO_CHAR(LOCALTIMESTAMP,'WW') AS BIGINT)
   AND MESSAGES.PROCESSINGSTATUSID IN(1,2,4);

   BEGIN
      SELECT SUM(TRANSACTIONS.TOTALAMOUNT) INTO STRICT MONTHLYAMOUNT FROM MPAY_TRANSACTIONS TRANSACTIONS, MPAY_ENDPOINTOPERATIONS OPERATIONS, MPAY_MPAYMESSAGES MESSAGES
      WHERE TRANSACTIONS.REFMESSAGEID = MESSAGES.ID
      AND MESSAGES.REFOPERATIONID = OPERATIONS.ID
      AND OPERATIONS.MESSAGETYPEID = TYPEID
      AND TRANSACTIONS.SENDERMOBILEID = MOBILEID
      AND EXTRACT(YEAR FROM TRANSACTIONS.TRANSDATE) =  EXTRACT(YEAR FROM LOCALTIMESTAMP)
      AND EXTRACT(MONTH FROM TRANSACTIONS.TRANSDATE) =  EXTRACT(MONTH FROM LOCALTIMESTAMP)
      AND TRANSACTIONS.PROCESSINGSTATUSID IN(1,2,4);
      IF MONTHLYAMOUNT IS NULL THEN
         MONTHLYAMOUNT := 0;
      END IF;
   END;

   SELECT COUNT(MESSAGES.ID) INTO STRICT MONTHLYCOUNT FROM MPAY_MPAYMESSAGES MESSAGES, MPAY_ENDPOINTOPERATIONS OPERATIONS
   WHERE MESSAGES.REFOPERATIONID = OPERATIONS.ID
   AND OPERATIONS.MESSAGETYPEID = TYPEID
   AND MESSAGES.SENDER = MOBILENUMBER
   AND EXTRACT(YEAR FROM MESSAGES.PROCESSINGSTAMP) =  EXTRACT(YEAR FROM LOCALTIMESTAMP)
   AND EXTRACT(MONTH FROM MESSAGES.PROCESSINGSTAMP) =  EXTRACT(MONTH FROM LOCALTIMESTAMP)
   AND MESSAGES.PROCESSINGSTATUSID IN(1,2,4);


   BEGIN
      SELECT SUM(TRANSACTIONS.TOTALAMOUNT) INTO STRICT YEARLYAMOUNT FROM MPAY_TRANSACTIONS TRANSACTIONS, MPAY_ENDPOINTOPERATIONS OPERATIONS, MPAY_MPAYMESSAGES MESSAGES
      WHERE TRANSACTIONS.REFMESSAGEID = MESSAGES.ID
      AND MESSAGES.REFOPERATIONID = OPERATIONS.ID
      AND OPERATIONS.MESSAGETYPEID = TYPEID
      AND TRANSACTIONS.SENDERMOBILEID = MOBILEID
      AND EXTRACT(YEAR FROM TRANSACTIONS.TRANSDATE) =  EXTRACT(YEAR FROM LOCALTIMESTAMP)
      AND TRANSACTIONS.PROCESSINGSTATUSID IN(1,2,4);
      IF YEARLYAMOUNT IS NULL THEN
         YEARLYAMOUNT := 0;
      END IF;
   END;


   SELECT COUNT(MESSAGES.ID) INTO STRICT YEARLYCOUNT FROM MPAY_MPAYMESSAGES MESSAGES, MPAY_ENDPOINTOPERATIONS OPERATIONS
   WHERE MESSAGES.REFOPERATIONID = OPERATIONS.ID
   AND OPERATIONS.MESSAGETYPEID = TYPEID
   AND MESSAGES.SENDER = MOBILENUMBER
   AND EXTRACT(YEAR FROM MESSAGES.PROCESSINGSTAMP) =  EXTRACT(YEAR FROM LOCALTIMESTAMP)
   AND MESSAGES.PROCESSINGSTATUSID IN(1,2,4);
   RETURN;
END; $BODY$
  LANGUAGE 'plpgsql' COST 100.0 SECURITY INVOKER;

--
-- getbalbywallettype
-- 

CREATE OR REPLACE FUNCTION getbalbywallettype(in wallet_type_code varchar)
  RETURNS numeric AS 
$BODY$
declare
            clients_total_balance numeric ;
            BEGIN
            SELECT sum(BALANCE)
            INTO clients_total_balance
            FROM MPAY_ACCOUNTS
            WHERE ID in (select refaccountid
                         from mpay_serviceaccounts ms
                         where serviceid in (select id
                                             from mpay_corpoarteservices mc
                                             where servicewallettypeid in
                                                   (select id from mpay_wallettypes mw where code = wallet_type_code)))
               OR ID IN (select refaccountid
                         from MPAY_MOBILEACCOUNTS ms
                         where mobileId in (select id
                                            from MPAY_CUSTOMERMOBILES mc
                                            where mobilewallettypeid in
                                                  (select id from mpay_wallettypes mw where code = wallet_type_code)));
            return clients_total_balance;
            END;
$BODY$
  LANGUAGE 'plpgsql' COST 100.0 SECURITY INVOKER;

--
-- getnewaccountnumber
-- 

CREATE OR REPLACE FUNCTION getnewaccountnumber(out rnewseqvalue int8)
  RETURNS int8 AS 
$BODY$
BEGIN
   SELECT NEXTVAL('ACCOUNT_NUMBER_SEQ') INTO STRICT RNEWSEQVALUE;
   RETURN;
END; $BODY$
  LANGUAGE 'plpgsql' COST 100.0 SECURITY INVOKER;

--
-- getnewreferencenumber
-- 

CREATE OR REPLACE FUNCTION getnewreferencenumber(out rnewseqvalue int8)
  RETURNS int8 AS 
$BODY$
BEGIN
   SELECT NEXTVAL('REFERENCE_NUMBER_SEQ') INTO STRICT RNEWSEQVALUE;
   RETURN;
END; $BODY$
  LANGUAGE 'plpgsql' COST 100.0 SECURITY INVOKER;

--
-- getnewseqval_epaymessageid
-- 

CREATE OR REPLACE FUNCTION getnewseqval_epaymessageid(out rnewseqvalue int8)
  RETURNS int8 AS 
$BODY$
BEGIN
   SELECT NEXTVAL('EPAY_MESSAGEID_SEQ') INTO STRICT RNEWSEQVALUE;
   RETURN;
END; $BODY$
  LANGUAGE 'plpgsql' COST 100.0 SECURITY INVOKER;

--
-- getnewseqval_messageid
-- 

CREATE OR REPLACE FUNCTION getnewseqval_messageid(out rnewseqvalue int8)
  RETURNS int8 AS 
$BODY$
BEGIN
   SELECT NEXTVAL('MPAY_MESSAGEID_SEQ') INTO STRICT RNEWSEQVALUE;
   RETURN;
END; $BODY$
  LANGUAGE 'plpgsql' COST 100.0 SECURITY INVOKER;

--
-- get_account_limits
-- 

CREATE OR REPLACE FUNCTION get_account_limits(in p_accountid int8, in p_messagetypeid int8)
  RETURNS TABLE (ryear int8, yearlycount int8, yearlyamount numeric, dailydate timestamp, dailycount int8, dailyamount numeric, weeknumber int8, weeklycount int8, weeklyamount numeric, rmonth int8, monthlycount int8, monthlyamount numeric, accountid int8, messagetypeid int8, messagetypegroupid int8, iscredit bool) AS 
$BODY$
BEGIN
    RETURN QUERY
    SELECT YEAR, mc.yearlycount, mc.yearlyamount, mc.dailydate, mc.dailycount, mc.dailyamount, mc.weeknumber, mc.weeklycount, mc.weeklyamount,
           MONTH, mc.monthlycount, mc.monthlyamount, mc.accountid, mc.messagetypeid, mc.messagetypegroupid, mc.iscredit
    FROM mpay_clientslimits mc
    WHERE mc.accountid = p_accountid AND mc.messagetypeid = p_messagetypeid;
END;
$BODY$
  LANGUAGE 'plpgsql' COST 100.0 SECURITY INVOKER;

--
-- get_group_account_limits
-- 

CREATE OR REPLACE FUNCTION get_group_account_limits(in p_accountid int8, in p_messagetypeid int8)
  RETURNS TABLE (ryear int8, yearlycount int8, yearlyamount numeric, dailydate timestamp, dailycount int8, dailyamount numeric, weeknumber int8, weeklycount int8, weeklyamount numeric, rmonth int8, monthlycount int8, monthlyamount numeric, accountid int8, messagetypeid int8, messagetypegroupid int8) AS 
$BODY$
BEGIN
    RETURN QUERY
    SELECT YEAR, mc.yearlycount, mc.yearlyamount, mc.dailydate, mc.dailycount, mc.dailyamount, mc.weeknumber, mc.weeklycount, mc.weeklyamount,
           MONTH, mc.monthlycount, mc.monthlyamount, mc.accountid, mc.messagetypeid, mc.messagetypegroupid
    FROM mpay_clientslimits mc
    WHERE mc.accountid = p_accountid AND mc.messagetypegroupid IN
          (SELECT msgetypegroup_id
           FROM mpay_msgetypegroupfinmsge mm
           WHERE finmsge_id = p_messagetypeid);
END;
$BODY$
  LANGUAGE 'plpgsql' COST 100.0 SECURITY INVOKER;

--
-- get_saib_virtual_iban_seq
-- 

CREATE OR REPLACE FUNCTION get_saib_virtual_iban_seq(out rnewseqvalue int8)
  RETURNS int8 AS 
$BODY$
BEGIN
   SELECT NEXTVAL('VIRTUAL_IBAN_SEQ') INTO STRICT RNEWSEQVALUE;
   RETURN;
END; $BODY$
  LANGUAGE 'plpgsql' COST 100.0 SECURITY INVOKER;

--
-- get_total_balance
-- 

CREATE OR REPLACE FUNCTION get_total_balance(out balance numeric)
  RETURNS numeric AS 
$BODY$
BEGIN
   SELECT SUM(accounts.balance) INTO STRICT BALANCE FROM MPAY_ACCOUNTS  accounts
   WHERE accounts.LEVEL1 is NULL
   OR accounts.LEVEL1 = 0;

   IF BALANCE IS NULL THEN
      BALANCE := 0;
   END IF;
   RETURN;
END; $BODY$
  LANGUAGE 'plpgsql' COST 100.0 SECURITY INVOKER;

--
-- mpay_agentinquiry
-- 

CREATE OR REPLACE FUNCTION mpay_agentinquiry(in mobnumber varchar)
  RETURNS refcursor AS 
$BODY$
       DECLARE

      ref refcursor; 
    BEGIN
      OPEN ref FOR select cor.description, cs.mobilenumber, cs.name,a.balance from mpay_corpoarteservices cs,mpay_corporates cor,mpay_serviceaccounts ac,mpay_Accounts a
where cor.id = cs.refcorporateid
and cs.id = ac.serviceid
and ac.refaccountid = a.id
and ac.isactive = 'true'
and ac.isregistered  ='true'
and cs.isactive = 'true'
and cs.isregistered = 'true'
and cor.isactive = 'true'
and cor.isregistered = 'true'
AND CS.MOBILENUMBER = mobnumber;   -- Open a cursor
RETURN ref;  -- Return the cursor to the caller
END;
$BODY$
  LANGUAGE 'plpgsql' COST 100.0 SECURITY INVOKER;

--
-- persist_message
-- 

CREATE OR REPLACE FUNCTION persist_message(out rmsg_id int8, in pz_created_by varchar, in pz_creation_date timestamp, in pz_org_id int8, in pz_tenant_id varchar, in pz_updated_by varchar, in pz_updating_date timestamp, in pmessageid varchar, in pprocessingstamp timestamp, in preference varchar, in prequesttoken varchar, in psender varchar, in pmessagetypeid int8, in pprocessingstatusid int8, in preasonid int8, in prefoperationid int8, out rrowcount float8)
  RETURNS record AS 
$BODY$
   DECLARE
   INS_ROW_COUNT NUMERIC;
BEGIN
   SELECT NEXTVAL('MPAY_MPAYMESSAGES_SEQ') INTO STRICT RMSG_ID;
   INSERT INTO MPAY_MPAYMESSAGES(ID, Z_CREATED_BY, Z_CREATION_DATE, Z_ORG_ID, Z_TENANT_ID,
    Z_UPDATED_BY, Z_UPDATING_DATE, MESSAGEID, PROCESSINGSTAMP, REFERENCE,
    REQUESTTOKEN, SENDER, MESSAGETYPEID, PROCESSINGSTATUSID, REASONID,
    REFOPERATIONID)
 VALUES(RMSG_ID,PZ_CREATED_BY, PZ_CREATION_DATE, PZ_ORG_ID, PZ_TENANT_ID,
    PZ_UPDATED_BY, PZ_UPDATING_DATE, PMESSAGEID, PPROCESSINGSTAMP, PREFERENCE,
    PREQUESTTOKEN, PSENDER, PMESSAGETYPEID, PPROCESSINGSTATUSID, PREASONID,
    PREFOPERATIONID);
    
   GET DIAGNOSTICS INS_ROW_COUNT = ROW_COUNT;
   RROWCOUNT := INS_ROW_COUNT;
   RETURN;
END; $BODY$
  LANGUAGE 'plpgsql' COST 100.0 SECURITY INVOKER;

--
-- postjournalvoucher
-- 

CREATE OR REPLACE FUNCTION postjournalvoucher(in accountid int8, in amount numeric, in jvid int8, out vrowscount int4, out vbalanceafter numeric, out vbalancebefore numeric)
  RETURNS record AS 
$BODY$
DECLARE
VTYPE int8;
    voucherId bigint;
	UPD_ROW_COUNT int;

BEGIN
SELECT BalanceTypeID, Balance
INTO vType, vBalanceBefore
FROM MPAY_Accounts
WHERE ID = accountId for update;
vBalanceAfter := vBalanceBefore + amount;

IF vType = 1 THEN
UPDATE MPAY_Accounts SET balance = vBalanceAfter
WHERE id = accountId AND vBalanceAfter >= 0;
ELSE IF vType = 2 THEN
UPDATE MPAY_Accounts SET balance = vBalanceAfter
WHERE id = accountId AND vBalanceAfter <= 0;
ELSE
UPDATE MPAY_Accounts SET balance = vBalanceAfter
WHERE id = accountId;
END IF;
END IF;
GET DIAGNOSTICS UPD_ROW_COUNT = ROW_COUNT;
vRowsCount := UPD_ROW_COUNT;
END;
$BODY$
  LANGUAGE 'plpgsql' COST 100.0 SECURITY INVOKER;

--
-- transaction_summary_report
-- 

CREATE OR REPLACE FUNCTION transaction_summary_report(in sessid varchar, out c_dbtransaction refcursor)
  RETURNS refcursor AS 
$BODY$
BEGIN
   OPEN C_DBTRANSACTION for
   SELECT DISTINCT(SELECT LOCALTIMESTAMP) AS CREATIONDATE  ,SESSIONID,SUM(TOTALAMOUNT) AS TOTALAMOUNT ,SUM(totalcharge) AS TOTALCHARGE,
    (select txdirection.id from MPAY_TRANSACTIONDIRECTIONS txDirection where txDirection.id = transaction.DIRECTIONID) AS DIRECTION,
    (select id from MPAY_MESSAGETYPES where id =(select messagetypeid from MPAY_ENDPOINTOPERATIONS where id = transaction.refoperationid)) AS MESSAGETYPE
   FROM
   MPAY_TRANSACTIONS transaction
   WHERE
   PROCESSINGSTATUSID = 1 AND SESSIONID = SESSID
   GROUP BY REFOPERATIONID,DIRECTIONID,SESSIONID;
   RETURN;
END; $BODY$
  LANGUAGE 'plpgsql' COST 100.0 SECURITY INVOKER;

--
-- trg_customerprofile_func
-- 

CREATE OR REPLACE FUNCTION trg_customerprofile_func()
  RETURNS trigger AS 
$BODY$
                BEGIN
                -- Update mpay_customermobiles
                UPDATE mpay_customermobiles
                SET refprofileid = NEW.refprofileid
                WHERE id = OLD.mobileid;

                -- Update MPAY_CUSTOMERS
                UPDATE MPAY_CUSTOMERS
                SET refprofileid = NEW.refprofileid
                WHERE id = (SELECT refcustomerid FROM mpay_customermobiles WHERE id = OLD.mobileid);

                RETURN NEW; -- important for AFTER trigger in PostgreSQL
                END;
                $BODY$
  LANGUAGE 'plpgsql' COST 100.0 SECURITY INVOKER;

--
-- updatebalances
-- 

CREATE OR REPLACE FUNCTION updatebalances(in accountid int8, in amount numeric, out vrowscount int4, out vbalancebefore numeric, out vbalanceafter numeric)
  RETURNS record AS 
$BODY$
   DECLARE
   VTYPE  int8;
   UPD_ROW_COUNT int;
BEGIN
   SELECT BalanceTypeID, Balance
   INTO STRICT VTYPE,VBALANCEBEFORE
   FROM MPAY_ACCOUNTS
   WHERE ID = ACCOUNTID for update;
   VBALANCEAFTER := VBALANCEBEFORE + AMOUNT;
   IF VTYPE = 1 THEN
      UPDATE MPAY_ACCOUNTS SET balance = VBALANCEAFTER
      WHERE id = ACCOUNTID AND VBALANCEAFTER >= 0;
      GET DIAGNOSTICS UPD_ROW_COUNT = ROW_COUNT;
      VROWSCOUNT := UPD_ROW_COUNT;
ELSE 
      IF VTYPE = 2 THEN
         UPDATE MPAY_ACCOUNTS SET balance = VBALANCEAFTER
         WHERE id = ACCOUNTID AND VBALANCEAFTER <= 0;
         GET DIAGNOSTICS UPD_ROW_COUNT = ROW_COUNT;
         VROWSCOUNT := UPD_ROW_COUNT;
   ELSE
         UPDATE MPAY_ACCOUNTS SET balance = VBALANCEAFTER
         WHERE id = ACCOUNTID;
         GET DIAGNOSTICS UPD_ROW_COUNT = ROW_COUNT;
         VROWSCOUNT := UPD_ROW_COUNT;
      END IF;
   END IF;
   RETURN;
END; $BODY$
  LANGUAGE 'plpgsql' COST 100.0 SECURITY INVOKER;

--
-- updateregfilerecordscount
-- 

CREATE OR REPLACE FUNCTION updateregfilerecordscount(in fileid float8, out vrowscount float8, out vrecordscount float8)
  RETURNS record AS 
$BODY$
   DECLARE
   UPD_ROW_COUNT NUMERIC;
BEGIN
   update MPAY_INTG_REG_FILES
   set REGFILEPROCESSEDRECORDS =(REGFILEPROCESSEDRECORDS+1)
   where ID = FILEID;
   GET DIAGNOSTICS UPD_ROW_COUNT = ROW_COUNT;
   VROWSCOUNT := UPD_ROW_COUNT;
SELECT REGFILEPROCESSEDRECORDS  INTO STRICT VRECORDSCOUNT  FROM MPAY_INTG_REG_FILES where ID = FILEID;
   RETURN;
END; $BODY$
  LANGUAGE 'plpgsql' COST 100.0 SECURITY INVOKER;

--
-- update_clients_limits
-- 

CREATE OR REPLACE FUNCTION update_clients_limits(in paccountid int8, in pmessagetypeid int8, in pamount numeric, in pcount int8, in pdate date, out rrowcount int4)
  RETURNS int4 AS 
$BODY$
   DECLARE
   RID  MPAY_CLIENTSLIMITS.ID%TYPE;
   VCOUNT  DOUBLE PRECISION;
   VYEAR  MPAY_CLIENTSLIMITS.YEAR%TYPE;
   VDAILYDATE  MPAY_CLIENTSLIMITS.DAILYDATE%TYPE;
   VWEEKNUMBER  MPAY_CLIENTSLIMITS.WEEKNUMBER%TYPE;
   VMONTH  MPAY_CLIENTSLIMITS.MONTH%TYPE;
   VDAILYCOUNT  MPAY_CLIENTSLIMITS.DAILYCOUNT%TYPE;
   VDAILYAMOUNT  MPAY_CLIENTSLIMITS.DAILYAMOUNT%TYPE;
   VWEEKLYCOUNT  MPAY_CLIENTSLIMITS.WEEKLYCOUNT%TYPE;
   VWEEKLYAMOUNT  MPAY_CLIENTSLIMITS.WEEKLYAMOUNT%TYPE;
   VMONTHLYCOUNT  MPAY_CLIENTSLIMITS.MONTHLYCOUNT%TYPE;
   VMONTHLYAMOUNT  MPAY_CLIENTSLIMITS.MONTHLYAMOUNT%TYPE;
   VYEARLYCOUNT  MPAY_CLIENTSLIMITS.YEARLYCOUNT%TYPE;
   VYEARLYAMOUNT  MPAY_CLIENTSLIMITS.YEARLYAMOUNT%TYPE;
   SWV_ROW_COUNT  int;
BEGIN
   SELECT COUNT(*) INTO STRICT VCOUNT FROM MPAY_CLIENTSLIMITS WHERE ACCOUNTID = PACCOUNTID AND MESSAGETYPEID = PMESSAGETYPEID;
   IF VCOUNT = 0 THEN
      SELECT NEXTVAL('MPAY_CLIENTSLIMITS_SEQ') INTO STRICT RID;
      INSERT INTO MPAY_CLIENTSLIMITS(ID,
       ACCOUNTID,
       MESSAGETYPEID,
       YEAR,
       DAILYDATE,
       DAILYCOUNT,
       DAILYAMOUNT,
       WEEKNUMBER,
       WEEKLYCOUNT,
       WEEKLYAMOUNT,
       MONTH,
       MONTHLYCOUNT,
       MONTHLYAMOUNT,
       YEARLYCOUNT,
       YEARLYAMOUNT)
    VALUES(RID,
     PACCOUNTID,
     PMESSAGETYPEID,
     EXTRACT(YEAR FROM PDATE),
     PDATE,
     PCOUNT,
     PAMOUNT,
     CAST(TO_CHAR(PDATE, 'WW') AS DOUBLE PRECISION),
     PCOUNT,
     PAMOUNT,
     EXTRACT(MONTH FROM PDATE),
     PCOUNT,
     PAMOUNT,
     PCOUNT,
     PAMOUNT);
ELSE
      SELECT YEAR, DAILYDATE, WEEKNUMBER, MONTH, DAILYCOUNT, DAILYAMOUNT, WEEKLYCOUNT, WEEKLYAMOUNT, MONTHLYCOUNT, MONTHLYAMOUNT, YEARLYCOUNT, YEARLYAMOUNT
      INTO STRICT VYEAR,VDAILYDATE,VWEEKNUMBER,VMONTH,VDAILYCOUNT,VDAILYAMOUNT,VWEEKLYCOUNT,
      VWEEKLYAMOUNT,VMONTHLYCOUNT,VMONTHLYAMOUNT,VYEARLYCOUNT,VYEARLYAMOUNT FROM MPAY_CLIENTSLIMITS WHERE ACCOUNTID = PACCOUNTID AND MESSAGETYPEID = PMESSAGETYPEID;
      IF VYEAR <> EXTRACT(YEAR FROM PDATE) THEN
         VYEAR := EXTRACT(YEAR FROM PDATE);
         VDAILYDATE := PDATE;
         VWEEKNUMBER := CAST(TO_CHAR(PDATE,'WW') AS DOUBLE PRECISION);
         VMONTH := EXTRACT(MONTH FROM PDATE);
         VDAILYCOUNT := PCOUNT;
         VWEEKLYCOUNT := PCOUNT;
         VMONTHLYCOUNT := PCOUNT;
         VYEARLYCOUNT := PCOUNT;
         VDAILYAMOUNT := PAMOUNT;
         VWEEKLYAMOUNT := PAMOUNT;
         VMONTHLYAMOUNT := PAMOUNT;
         VYEARLYAMOUNT := PAMOUNT;
   ELSE
         VYEARLYCOUNT := VYEARLYCOUNT + PCOUNT;
         VYEARLYAMOUNT := VYEARLYAMOUNT + PAMOUNT;
         IF VDAILYDATE <> PDATE THEN
            VDAILYDATE := PDATE;
            VDAILYCOUNT := PCOUNT;
            VDAILYAMOUNT := PAMOUNT;
      ELSE
            VDAILYCOUNT := VDAILYCOUNT + PCOUNT;
            VDAILYAMOUNT := VDAILYAMOUNT + PAMOUNT;
         END IF;
         IF VWEEKNUMBER <> CAST(TO_CHAR(PDATE,'WW') AS DOUBLE PRECISION) THEN
            VWEEKNUMBER := CAST(TO_CHAR(PDATE,'WW') AS DOUBLE PRECISION);
            VWEEKLYCOUNT := PCOUNT;
            VWEEKLYAMOUNT := PAMOUNT;
      ELSE
            VWEEKLYCOUNT := VWEEKLYCOUNT + PCOUNT;
            VWEEKLYAMOUNT := VWEEKLYAMOUNT + PAMOUNT;
         END IF;
         IF VMONTH <> EXTRACT(MONTH FROM PDATE) THEN
            VMONTH := EXTRACT(MONTH FROM PDATE);
            VMONTHLYCOUNT := PCOUNT;
            VMONTHLYAMOUNT := PAMOUNT;
      ELSE
            VMONTHLYCOUNT := VMONTHLYCOUNT + PCOUNT;
            VMONTHLYAMOUNT := VMONTHLYAMOUNT + PAMOUNT;
         END IF;
      END IF;
      IF VDAILYCOUNT < 0 THEN
         VDAILYCOUNT := 0;
      END IF;
      IF VDAILYAMOUNT < 0 THEN
         VDAILYAMOUNT := 0;
      END IF;
      IF VWEEKLYCOUNT < 0 THEN
         VWEEKLYCOUNT := 0;
      END IF;
      IF VWEEKLYAMOUNT < 0 THEN
         VWEEKLYAMOUNT := 0;
      END IF;
      IF VMONTHLYCOUNT < 0 THEN
         VMONTHLYCOUNT := 0;
      END IF;
      IF VMONTHLYAMOUNT < 0 THEN
         VMONTHLYAMOUNT := 0;
      END IF;
      IF VYEARLYCOUNT < 0 THEN
         VYEARLYCOUNT := 0;
      END IF;
      IF VYEARLYAMOUNT < 0 THEN
         VYEARLYAMOUNT := 0;
      END IF;
      UPDATE MPAY_CLIENTSLIMITS
      SET
      YEAR = VYEAR,DAILYDATE = VDAILYDATE,DAILYCOUNT = VDAILYCOUNT,DAILYAMOUNT = VDAILYAMOUNT,
      WEEKNUMBER = VWEEKNUMBER,WEEKLYCOUNT = VWEEKLYCOUNT,
      WEEKLYAMOUNT = VWEEKLYAMOUNT,MONTH = VMONTH,MONTHLYCOUNT = VMONTHLYCOUNT,
      MONTHLYAMOUNT = VMONTHLYAMOUNT,YEARLYCOUNT = VYEARLYCOUNT,YEARLYAMOUNT = VYEARLYAMOUNT
      WHERE ACCOUNTID = PACCOUNTID AND  MESSAGETYPEID = PMESSAGETYPEID;
     GET DIAGNOSTICS SWV_ROW_COUNT = ROW_COUNT;
   END IF;
   RROWCOUNT := SWV_ROW_COUNT;
   RETURN;
END; $BODY$
  LANGUAGE 'plpgsql' COST 100.0 SECURITY INVOKER;

--
-- update_clients_limits
-- 

CREATE OR REPLACE FUNCTION update_clients_limits(in paccountid int8, in pmessagetypeid int8, in pmessagetypegroupid int8, in pamount numeric, in pcount int8, in pdate date, in piscredit bool, out rrowcount int4)
  RETURNS int4 AS 
$BODY$
   DECLARE
   RID  MPAY_CLIENTSLIMITS.ID%TYPE;
   VCOUNT  DOUBLE PRECISION;
   VYEAR  MPAY_CLIENTSLIMITS.YEAR%TYPE;
   VDAILYDATE  MPAY_CLIENTSLIMITS.DAILYDATE%TYPE;
   VWEEKNUMBER  MPAY_CLIENTSLIMITS.WEEKNUMBER%TYPE;
   VMONTH  MPAY_CLIENTSLIMITS.MONTH%TYPE;
   VDAILYCOUNT  MPAY_CLIENTSLIMITS.DAILYCOUNT%TYPE;
   VDAILYAMOUNT  MPAY_CLIENTSLIMITS.DAILYAMOUNT%TYPE;
   VWEEKLYCOUNT  MPAY_CLIENTSLIMITS.WEEKLYCOUNT%TYPE;
   VWEEKLYAMOUNT  MPAY_CLIENTSLIMITS.WEEKLYAMOUNT%TYPE;
   VMONTHLYCOUNT  MPAY_CLIENTSLIMITS.MONTHLYCOUNT%TYPE;
   VMONTHLYAMOUNT  MPAY_CLIENTSLIMITS.MONTHLYAMOUNT%TYPE;
   VYEARLYCOUNT  MPAY_CLIENTSLIMITS.YEARLYCOUNT%TYPE;
   VYEARLYAMOUNT  MPAY_CLIENTSLIMITS.YEARLYAMOUNT%TYPE;
   VISCREDIT  MPAY_CLIENTSLIMITS.ISCREDIT%TYPE;
   SWV_ROW_COUNT  int;
BEGIN
   SELECT COUNT(*) INTO STRICT VCOUNT FROM MPAY_CLIENTSLIMITS where iscredit = piscredit AND ACCOUNTID = PACCOUNTID AND (MESSAGETYPEID = pMESSAGETYPEID OR MESSAGETYPEGROUPID = pMESSAGETYPEGROUPID);
   IF VCOUNT = 0 THEN
      SELECT NEXTVAL('MPAY_CLIENTSLIMITS_SEQ') INTO STRICT RID;
      INSERT INTO MPAY_CLIENTSLIMITS(ID,
       ACCOUNTID,
       MESSAGETYPEID,
       MESSAGETYPEGROUPID,
       YEAR,
       DAILYDATE,
       DAILYCOUNT,
       DAILYAMOUNT,
       WEEKNUMBER,
       WEEKLYCOUNT,
       WEEKLYAMOUNT,
       MONTH,
       MONTHLYCOUNT,
       MONTHLYAMOUNT,
       YEARLYCOUNT,
       YEARLYAMOUNT,
       ISCREDIT)
    VALUES(RID,
     PACCOUNTID,
     PMESSAGETYPEID,
     PMESSAGETYPEGROUPID,
     EXTRACT(YEAR FROM PDATE),
     PDATE,
     PCOUNT,
     PAMOUNT,
     CAST(TO_CHAR(PDATE, 'WW') AS DOUBLE PRECISION),
     PCOUNT,
     PAMOUNT,
     EXTRACT(MONTH FROM PDATE),
     PCOUNT,
     PAMOUNT,
     PCOUNT,
     PAMOUNT,
     PISCREDIT);
ELSE
      SELECT YEAR, DAILYDATE, WEEKNUMBER, MONTH, DAILYCOUNT, DAILYAMOUNT, WEEKLYCOUNT, WEEKLYAMOUNT, MONTHLYCOUNT, MONTHLYAMOUNT, YEARLYCOUNT, YEARLYAMOUNT
      INTO STRICT VYEAR,VDAILYDATE,VWEEKNUMBER,VMONTH,VDAILYCOUNT,VDAILYAMOUNT,VWEEKLYCOUNT,
      VWEEKLYAMOUNT,VMONTHLYCOUNT,VMONTHLYAMOUNT,VYEARLYCOUNT,VYEARLYAMOUNT, VISCREDIT FROM MPAY_CLIENTSLIMITS WHERE iscredit = piscredit and ACCOUNTID = PACCOUNTID AND MESSAGETYPEID = PMESSAGETYPEID;
      IF VYEAR <> EXTRACT(YEAR FROM PDATE) THEN
         VYEAR := EXTRACT(YEAR FROM PDATE);
         VDAILYDATE := PDATE;
         VWEEKNUMBER := CAST(TO_CHAR(PDATE,'WW') AS DOUBLE PRECISION);
         VMONTH := EXTRACT(MONTH FROM PDATE);
         VDAILYCOUNT := PCOUNT;
         VWEEKLYCOUNT := PCOUNT;
         VMONTHLYCOUNT := PCOUNT;
         VYEARLYCOUNT := PCOUNT;
         VDAILYAMOUNT := PAMOUNT;
         VWEEKLYAMOUNT := PAMOUNT;
         VMONTHLYAMOUNT := PAMOUNT;
         VYEARLYAMOUNT := PAMOUNT;
   ELSE
         VYEARLYCOUNT := VYEARLYCOUNT + PCOUNT;
         VYEARLYAMOUNT := VYEARLYAMOUNT + PAMOUNT;
         IF VDAILYDATE <> PDATE THEN
            VDAILYDATE := PDATE;
            VDAILYCOUNT := PCOUNT;
            VDAILYAMOUNT := PAMOUNT;
      ELSE
            VDAILYCOUNT := VDAILYCOUNT + PCOUNT;
            VDAILYAMOUNT := VDAILYAMOUNT + PAMOUNT;
         END IF;
         IF VWEEKNUMBER <> CAST(TO_CHAR(PDATE,'WW') AS DOUBLE PRECISION) THEN
            VWEEKNUMBER := CAST(TO_CHAR(PDATE,'WW') AS DOUBLE PRECISION);
            VWEEKLYCOUNT := PCOUNT;
            VWEEKLYAMOUNT := PAMOUNT;
      ELSE
            VWEEKLYCOUNT := VWEEKLYCOUNT + PCOUNT;
            VWEEKLYAMOUNT := VWEEKLYAMOUNT + PAMOUNT;
         END IF;
         IF VMONTH <> EXTRACT(MONTH FROM PDATE) THEN
            VMONTH := EXTRACT(MONTH FROM PDATE);
            VMONTHLYCOUNT := PCOUNT;
            VMONTHLYAMOUNT := PAMOUNT;
      ELSE
            VMONTHLYCOUNT := VMONTHLYCOUNT + PCOUNT;
            VMONTHLYAMOUNT := VMONTHLYAMOUNT + PAMOUNT;
         END IF;
      END IF;
      IF VDAILYCOUNT < 0 THEN
         VDAILYCOUNT := 0;
      END IF;
      IF VDAILYAMOUNT < 0 THEN
         VDAILYAMOUNT := 0;
      END IF;
      IF VWEEKLYCOUNT < 0 THEN
         VWEEKLYCOUNT := 0;
      END IF;
      IF VWEEKLYAMOUNT < 0 THEN
         VWEEKLYAMOUNT := 0;
      END IF;
      IF VMONTHLYCOUNT < 0 THEN
         VMONTHLYCOUNT := 0;
      END IF;
      IF VMONTHLYAMOUNT < 0 THEN
         VMONTHLYAMOUNT := 0;
      END IF;
      IF VYEARLYCOUNT < 0 THEN
         VYEARLYCOUNT := 0;
      END IF;
      IF VYEARLYAMOUNT < 0 THEN
         VYEARLYAMOUNT := 0;
      END IF;
      UPDATE MPAY_CLIENTSLIMITS
      SET
      YEAR = VYEAR,DAILYDATE = VDAILYDATE,DAILYCOUNT = VDAILYCOUNT,DAILYAMOUNT = VDAILYAMOUNT,
      WEEKNUMBER = VWEEKNUMBER,WEEKLYCOUNT = VWEEKLYCOUNT,
      WEEKLYAMOUNT = VWEEKLYAMOUNT,MONTH = VMONTH,MONTHLYCOUNT = VMONTHLYCOUNT,
      MONTHLYAMOUNT = VMONTHLYAMOUNT,YEARLYCOUNT = VYEARLYCOUNT,YEARLYAMOUNT = VYEARLYAMOUNT
      WHERE ACCOUNTID = PACCOUNTID AND iscredit = piscredit AND (MESSAGETYPEID = pMESSAGETYPEID OR MESSAGETYPEGROUPID = pMESSAGETYPEGROUPID);
     GET DIAGNOSTICS SWV_ROW_COUNT = ROW_COUNT;
   END IF;
   RROWCOUNT := SWV_ROW_COUNT;
   RETURN;
END; $BODY$
  LANGUAGE 'plpgsql' COST 100.0 SECURITY INVOKER;

--
-- update_clients_limits
-- 

CREATE OR REPLACE FUNCTION update_clients_limits(in paccountid int8, in pmessagetypeid int8, in pmessagetypegroupid int8, in pamount numeric, in pcount int8, in pdate date, out rrowcount int4)
  RETURNS int4 AS 
$BODY$
   DECLARE
   RID  MPAY_CLIENTSLIMITS.ID%TYPE;
   VCOUNT  DOUBLE PRECISION;
   VYEAR  MPAY_CLIENTSLIMITS.YEAR%TYPE;
   VDAILYDATE  MPAY_CLIENTSLIMITS.DAILYDATE%TYPE;
   VWEEKNUMBER  MPAY_CLIENTSLIMITS.WEEKNUMBER%TYPE;
   VMONTH  MPAY_CLIENTSLIMITS.MONTH%TYPE;
   VDAILYCOUNT  MPAY_CLIENTSLIMITS.DAILYCOUNT%TYPE;
   VDAILYAMOUNT  MPAY_CLIENTSLIMITS.DAILYAMOUNT%TYPE;
   VWEEKLYCOUNT  MPAY_CLIENTSLIMITS.WEEKLYCOUNT%TYPE;
   VWEEKLYAMOUNT  MPAY_CLIENTSLIMITS.WEEKLYAMOUNT%TYPE;
   VMONTHLYCOUNT  MPAY_CLIENTSLIMITS.MONTHLYCOUNT%TYPE;
   VMONTHLYAMOUNT  MPAY_CLIENTSLIMITS.MONTHLYAMOUNT%TYPE;
   VYEARLYCOUNT  MPAY_CLIENTSLIMITS.YEARLYCOUNT%TYPE;
   VYEARLYAMOUNT  MPAY_CLIENTSLIMITS.YEARLYAMOUNT%TYPE;
   SWV_ROW_COUNT  int;
BEGIN
   SELECT COUNT(*) INTO STRICT VCOUNT FROM MPAY_CLIENTSLIMITS WHERE ACCOUNTID = PACCOUNTID AND (MESSAGETYPEID = pMESSAGETYPEID OR MESSAGETYPEGROUPID = pMESSAGETYPEGROUPID);
   IF VCOUNT = 0 THEN
      SELECT NEXTVAL('MPAY_CLIENTSLIMITS_SEQ') INTO STRICT RID;
      INSERT INTO MPAY_CLIENTSLIMITS(ID,
       ACCOUNTID,
       MESSAGETYPEID,
       MESSAGETYPEGROUPID,
       YEAR,
       DAILYDATE,
       DAILYCOUNT,
       DAILYAMOUNT,
       WEEKNUMBER,
       WEEKLYCOUNT,
       WEEKLYAMOUNT,
       MONTH,
       MONTHLYCOUNT,
       MONTHLYAMOUNT,
       YEARLYCOUNT,
       YEARLYAMOUNT)
    VALUES(RID,
     PACCOUNTID,
     PMESSAGETYPEID,
     PMESSAGETYPEGROUPID,
     EXTRACT(YEAR FROM PDATE),
     PDATE,
     PCOUNT,
     PAMOUNT,
     CAST(TO_CHAR(PDATE, 'WW') AS DOUBLE PRECISION),
     PCOUNT,
     PAMOUNT,
     EXTRACT(MONTH FROM PDATE),
     PCOUNT,
     PAMOUNT,
     PCOUNT,
     PAMOUNT);
ELSE
      SELECT YEAR, DAILYDATE, WEEKNUMBER, MONTH, DAILYCOUNT, DAILYAMOUNT, WEEKLYCOUNT, WEEKLYAMOUNT, MONTHLYCOUNT, MONTHLYAMOUNT, YEARLYCOUNT, YEARLYAMOUNT
      INTO STRICT VYEAR,VDAILYDATE,VWEEKNUMBER,VMONTH,VDAILYCOUNT,VDAILYAMOUNT,VWEEKLYCOUNT,
      VWEEKLYAMOUNT,VMONTHLYCOUNT,VMONTHLYAMOUNT,VYEARLYCOUNT,VYEARLYAMOUNT FROM MPAY_CLIENTSLIMITS WHERE ACCOUNTID = PACCOUNTID AND MESSAGETYPEID = PMESSAGETYPEID;
      IF VYEAR <> EXTRACT(YEAR FROM PDATE) THEN
         VYEAR := EXTRACT(YEAR FROM PDATE);
         VDAILYDATE := PDATE;
         VWEEKNUMBER := CAST(TO_CHAR(PDATE,'WW') AS DOUBLE PRECISION);
         VMONTH := EXTRACT(MONTH FROM PDATE);
         VDAILYCOUNT := PCOUNT;
         VWEEKLYCOUNT := PCOUNT;
         VMONTHLYCOUNT := PCOUNT;
         VYEARLYCOUNT := PCOUNT;
         VDAILYAMOUNT := PAMOUNT;
         VWEEKLYAMOUNT := PAMOUNT;
         VMONTHLYAMOUNT := PAMOUNT;
         VYEARLYAMOUNT := PAMOUNT;
   ELSE
         VYEARLYCOUNT := VYEARLYCOUNT + PCOUNT;
         VYEARLYAMOUNT := VYEARLYAMOUNT + PAMOUNT;
         IF VDAILYDATE <> PDATE THEN
            VDAILYDATE := PDATE;
            VDAILYCOUNT := PCOUNT;
            VDAILYAMOUNT := PAMOUNT;
      ELSE
            VDAILYCOUNT := VDAILYCOUNT + PCOUNT;
            VDAILYAMOUNT := VDAILYAMOUNT + PAMOUNT;
         END IF;
         IF VWEEKNUMBER <> CAST(TO_CHAR(PDATE,'WW') AS DOUBLE PRECISION) THEN
            VWEEKNUMBER := CAST(TO_CHAR(PDATE,'WW') AS DOUBLE PRECISION);
            VWEEKLYCOUNT := PCOUNT;
            VWEEKLYAMOUNT := PAMOUNT;
      ELSE
            VWEEKLYCOUNT := VWEEKLYCOUNT + PCOUNT;
            VWEEKLYAMOUNT := VWEEKLYAMOUNT + PAMOUNT;
         END IF;
         IF VMONTH <> EXTRACT(MONTH FROM PDATE) THEN
            VMONTH := EXTRACT(MONTH FROM PDATE);
            VMONTHLYCOUNT := PCOUNT;
            VMONTHLYAMOUNT := PAMOUNT;
      ELSE
            VMONTHLYCOUNT := VMONTHLYCOUNT + PCOUNT;
            VMONTHLYAMOUNT := VMONTHLYAMOUNT + PAMOUNT;
         END IF;
      END IF;
      IF VDAILYCOUNT < 0 THEN
         VDAILYCOUNT := 0;
      END IF;
      IF VDAILYAMOUNT < 0 THEN
         VDAILYAMOUNT := 0;
      END IF;
      IF VWEEKLYCOUNT < 0 THEN
         VWEEKLYCOUNT := 0;
      END IF;
      IF VWEEKLYAMOUNT < 0 THEN
         VWEEKLYAMOUNT := 0;
      END IF;
      IF VMONTHLYCOUNT < 0 THEN
         VMONTHLYCOUNT := 0;
      END IF;
      IF VMONTHLYAMOUNT < 0 THEN
         VMONTHLYAMOUNT := 0;
      END IF;
      IF VYEARLYCOUNT < 0 THEN
         VYEARLYCOUNT := 0;
      END IF;
      IF VYEARLYAMOUNT < 0 THEN
         VYEARLYAMOUNT := 0;
      END IF;
      UPDATE MPAY_CLIENTSLIMITS
      SET
      YEAR = VYEAR,DAILYDATE = VDAILYDATE,DAILYCOUNT = VDAILYCOUNT,DAILYAMOUNT = VDAILYAMOUNT,
      WEEKNUMBER = VWEEKNUMBER,WEEKLYCOUNT = VWEEKLYCOUNT,
      WEEKLYAMOUNT = VWEEKLYAMOUNT,MONTH = VMONTH,MONTHLYCOUNT = VMONTHLYCOUNT,
      MONTHLYAMOUNT = VMONTHLYAMOUNT,YEARLYCOUNT = VYEARLYCOUNT,YEARLYAMOUNT = VYEARLYAMOUNT
      WHERE ACCOUNTID = PACCOUNTID AND  (MESSAGETYPEID = pMESSAGETYPEID OR MESSAGETYPEGROUPID = pMESSAGETYPEGROUPID);
     GET DIAGNOSTICS SWV_ROW_COUNT = ROW_COUNT;
   END IF;
   RROWCOUNT := SWV_ROW_COUNT;
   RETURN;
END; $BODY$
  LANGUAGE 'plpgsql' COST 100.0 SECURITY INVOKER;
  

---GetNextAuthNumber

CREATE OR REPLACE FUNCTION getnextauthnumber() returns character varying
    language plpgsql
as
$$
DECLARE
    authNumber VARCHAR;
    seq_val BIGINT;
BEGIN
    seq_val := nextval('external_ref_sequence');

    authNumber :=
            CHR(ASCII('A') + MOD(((seq_val/26/26/26/26/26)::int), 26)) ||
            CHR(ASCII('A') + MOD(((seq_val/26/26/26/26)::int), 26)) ||
            CHR(ASCII('A') + MOD(((seq_val/26/26/26)::int), 26)) ||
            CHR(ASCII('A') + MOD(((seq_val/26/26)::int), 26)) ||
            CHR(ASCII('A') + MOD(((seq_val/26)::int), 26)) ||
            CHR(ASCII('A') + MOD(seq_val::int, 26));
    
    RETURN authNumber;
END;
$$;

---GET_MEPS_TRX_DETAILS

CREATE OR REPLACE FUNCTION GET_MEPS_TRX_DETAILS(mpayreference VARCHAR)
RETURNS TABLE (
    hasHoldAmount NUMERIC,
    merchantName VARCHAR,
    cardNumber VARCHAR,
    terminalLocation VARCHAR,
    rrn VARCHAR,
    goodFaithRef VARCHAR,
    goodFaithBy NUMERIC
) AS $$
BEGIN
    RETURN QUERY
    SELECT
        mt.HASHOLDAMOUNT,
        mt.MERCHANTNAME,
        mt.CARDNUMBER,
        mt.TERMINALLOCATION,
        mt.RETRIEVALREFNUMBER,
        mt.GOODFAITHREF,
        mt.GOODFAITHBYID
    FROM MEPS_TRANSACTIONS mt
    WHERE mt.MPAYTRXREF = mpayreference;
END;
$$ LANGUAGE plpgsql;


---GET_SUM_OF_HOLD_AMOUNT

CREATE OR REPLACE FUNCTION GET_SUM_OF_HOLD_AMOUNT(receiverIdentifier VARCHAR)
RETURNS NUMERIC AS $$
DECLARE
    sumOfHoldAmount NUMERIC;
BEGIN
    SELECT COALESCE(SUM(hr.HOLDAMOUNT), 0) INTO sumOfHoldAmount
    FROM MEPS_HOLDRECORDS hr
    WHERE hr.TRANSACTIONREFERENCEID IN (
        SELECT mt.ID
        FROM MEPS_TRANSACTIONS mt
        WHERE mt.HASHOLDAMOUNT = 1
        AND mt.EXTRAFIELD1 = receiverIdentifier
    );
    
    RETURN sumOfHoldAmount;
END;
$$ LANGUAGE plpgsql;


---INCREASE_TOTAL_HOLD_AMOUNTS

CREATE OR REPLACE FUNCTION INCREASE_TOTAL_HOLD_AMOUNTS(
    isMobile NUMERIC,
    transactionRef VARCHAR,
    holdAmount NUMERIC
)
RETURNS INTEGER AS $$
DECLARE
    rows_updated INTEGER;
BEGIN
    IF isMobile > 0 THEN
        UPDATE mpay_accounts
        SET TOTALHOLDAMOUNTS = TOTALHOLDAMOUNTS + holdAmount
        WHERE id = (
            SELECT ma.refaccountid
            FROM MPAY_MOBILEACCOUNTS ma
            WHERE ma.id = (
                SELECT mt.RECEIVERMOBILEACCOUNTID
                FROM mpay_transactions mt
                WHERE mt.REFERENCE = transactionRef
            )
        );
    ELSE
        UPDATE mpay_accounts
        SET TOTALHOLDAMOUNTS = TOTALHOLDAMOUNTS + holdAmount
        WHERE id = (
            SELECT sa.refaccountid
            FROM MPAY_SERVICEACCOUNTS sa
            WHERE sa.id = (
                SELECT mt.RECEIVERSERVICEACCOUNTID
                FROM mpay_transactions mt
                WHERE mt.REFERENCE = transactionRef
            )
        );
    END IF;
    
    GET DIAGNOSTICS rows_updated = ROW_COUNT;
    RETURN rows_updated;
END;
$$ LANGUAGE plpgsql;

---DECREASE_TOTAL_HOLD_AMOUNTS

CREATE OR REPLACE FUNCTION DECREASE_TOTAL_HOLD_AMOUNTS(
    isMobile NUMERIC,
    transactionRef VARCHAR,
    holdAmount NUMERIC
)
RETURNS INTEGER AS $$
DECLARE
    rows_updated INTEGER;
BEGIN
    IF isMobile > 0 THEN
        UPDATE mpay_accounts
        SET TOTALHOLDAMOUNTS = TOTALHOLDAMOUNTS - holdAmount
        WHERE id = (
            SELECT ma.refaccountid
            FROM MPAY_MOBILEACCOUNTS ma
            WHERE ma.id = (
                SELECT mt.RECEIVERMOBILEACCOUNTID
                FROM mpay_transactions mt
                WHERE mt.REFERENCE = transactionRef
            )
        );
    ELSE
        UPDATE mpay_accounts
        SET TOTALHOLDAMOUNTS = TOTALHOLDAMOUNTS - holdAmount
        WHERE id = (
            SELECT sa.refaccountid
            FROM MPAY_SERVICEACCOUNTS sa
            WHERE sa.id = (
                SELECT mt.RECEIVERSERVICEACCOUNTID
                FROM mpay_transactions mt
                WHERE mt.REFERENCE = transactionRef
            )
        );
    END IF;
    
    GET DIAGNOSTICS rows_updated = ROW_COUNT;
    RETURN rows_updated;
END;
$$ LANGUAGE plpgsql;




